"""add surveys table

Revision ID: 2de4a3c34071
Revises: 55cb2bcd79ac
Create Date: 2026-05-30 14:12:03.473614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de4a3c34071'
down_revision: Union[str, Sequence[str], None] = '55cb2bcd79ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('recall', sa.String(), nullable=False),
    sa.Column('brand_score', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveys')
    # ### end Alembic commands ###
