"""add scene_data to ads

Revision ID: 5f63608c71c3
Revises: 32cfb34f0a57
Create Date: 2026-05-28 15:22:43.931095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f63608c71c3'
down_revision: Union[str, Sequence[str], None] = '32cfb34f0a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('scene_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'scene_data')
    # ### end Alembic commands ###
